name: dartpy
description: A starting point for Dart libraries or applications.
version: 0.0.1+4
homepage: http://github.com/TimWhiting/dartpy

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  path: ^1.8.0
  ffi: ^2.0.1
  freezed_annotation: ^0.14.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
  ffigen: 
  freezed: ^0.14.0
  build_runner: 

